# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/86156/Desktop/calab/calab-68/Cooperative_project/prj7_exp23/mycpu_env/soc_verify/soc_axi/run_vivado/project/loongson.srcs/sources_1/ip/data_bank_ram/data_bank_ram.xci
# IP: The module: 'data_bank_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/86156/Desktop/calab/calab-68/Cooperative_project/prj7_exp23/mycpu_env/soc_verify/soc_axi/run_vivado/project/loongson.gen/sources_1/ip/data_bank_ram/data_bank_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_bank_ram'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/86156/Desktop/calab/calab-68/Cooperative_project/prj7_exp23/mycpu_env/soc_verify/soc_axi/run_vivado/project/loongson.srcs/sources_1/ip/data_bank_ram/data_bank_ram.xci
# IP: The module: 'data_bank_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/86156/Desktop/calab/calab-68/Cooperative_project/prj7_exp23/mycpu_env/soc_verify/soc_axi/run_vivado/project/loongson.gen/sources_1/ip/data_bank_ram/data_bank_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_bank_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
